image: atlassian/default-image:3

definitions:
  steps:
    - step: &build
        name: Build
        size: 4x
        script:
          - export SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
          - bash ./run.sh build
        services:
          - docker
    - step: &sonarqube-scan
        name: SonarQube analysis
        script:
          - pipe: sonarsource/sonarqube-scan:2.0.1
            variables:
              SONAR_HOST_URL: ${SONAR_HOST_URL}
              SONAR_TOKEN: ${SONAR_TOKEN}
  caches:
    sonar: ~/.sonar  

clone:
  depth: full

pipelines:
  branches:
    develop:
      - step: 
          name: Patch version update
          script: 
           - bash version.sh patch
      - step: *build
      - step:
          name: Deploy Dev
          deployment: Development
          image: google/cloud-sdk:alpine
          script:
            - gcloud components install kubectl
            - bash ./run.sh deploy-dev
      - step: *sonarqube-scan
    release/v*-*-*-prod:
      - step: *build
      - step:
          name: Deploy Prod
          deployment: Production
          image: google/cloud-sdk:alpine
          script:
            - gcloud components install kubectl
            - bash ./run.sh deploy-prod
      - step: *sonarqube-scan
    release/v*-*-*-rc:
      - step: *build
      - step:
          name: Deploy Release
          deployment: Release
          image: google/cloud-sdk:alpine
          script:
            - gcloud components install kubectl
            - bash ./run.sh deploy-rel
      - step: *sonarqube-scan
