services:
  traefik:
    image: traefik:v3.6.4
    container_name: traefik
    restart: unless-stopped
    logging:
      options:
        max-size: "50m"
        max-file: "3"
    command:
      - --log.level=INFO
      - --providers.docker=true
      - --providers.docker.exposedbydefault=true
      - --entryPoints.web.address=:80
      - --entryPoints.web.http.redirections.entryPoint.to=websecure
      - --entryPoints.web.http.redirections.entryPoint.scheme=https
      - --entryPoints.websecure.address=:443
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --certificatesresolvers.le.acme.email=admin@talkingdb.io
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker_net

networks:
  docker_net:
    name: docker_default
    driver: bridge
