version: "3"

services:
  traefik:
    image: traefik:v1.7-alpine
    container_name: traefik
    logging:
      options:
        max-size: "50m"
        max-file: "3"
    command: >
      --logLevel='INFO' --web --InsecureSkipVerify=true --defaultentrypoints=https,http --entryPoints='Name:http Address::80' --entryPoints='Name:https Address::443 TLS Redirect.EntryPoint:http' --retry --docker --docker.endpoint='unix:///var/run/docker.sock' --docker.exposedbydefault=true --docker.watch=true
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.port=8080"
    networks:
      - docker_net

  llm-chatbot:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: llm-chatbot
    logging:
      options:
        max-size: "50m"
        max-file: "3"
    command: [ "npm", "run", "dev" ]
    labels:
      - "traefik.port=80"
      - "traefik.enable=true"
      - "traefik.backend=llm-chatbot"
      - "traefik.frontend.rule=Host:${CHAT_HOST}"
      - "traefik.protocol=http"
    networks:
      - docker_net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    logging:
      options:
        max-size: "50m"
        max-file: "3"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PSSWD}
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - docker_net

volumes:
  mongodb-data:


networks:
  docker_net:
    driver: bridge
