version: "3"

services:
  llm-chatbot:
    image: $IMAGE_TAG
    container_name: llm-chatbot-$REL_TAG
    restart: always
    logging:
      options:
        max-size: "50m"
        max-file: "3"
    command: [ "npm", "run", "dev" ]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.llm-chatbot-$REL_TAG.rule=Host(`$HOST_NAME`)"
      - "traefik.http.routers.llm-chatbot-$REL_TAG.entrypoints=websecure"
      - "traefik.http.routers.llm-chatbot-$REL_TAG.tls=true"
      - "traefik.http.routers.llm-chatbot-$REL_TAG.tls.certresolver=myresolver"
      - "traefik.http.services.llm-chatbot-$REL_TAG-service.loadbalancer.server.port=80"
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - PINECONE_API_KEY=$PINECONE_API_KEY
      - PINECONE_ENVIRONMENT=$PINECONE_ENVIRONMENT
      - PINECONE_INDEX_NAME=$PINECONE_INDEX_NAME
      - NEXT_PUBLIC_BACKEND_CONNECTOR_HOST=$NEXT_PUBLIC_BACKEND_CONNECTOR_HOST
      - NEXT_PUBLIC_BACKEND_CONNECTOR_KEY=$NEXT_PUBLIC_BACKEND_CONNECTOR_KEY
      - NEXT_PUBLIC_HI_MESSAGE_RESPONSE=$NEXT_PUBLIC_HI_MESSAGE_RESPONSE
      - NEXT_PUBLIC_BACKEND_CONNECTOR_WHATSAPPHOST=$NEXT_PUBLIC_BACKEND_CONNECTOR_WHATSAPPHOST
    networks:
      - doc-search-network

networks:
  doc-search-network:
    external: true
