apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-$APP
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-$APP
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP
  template:
    metadata:
      labels:
        app: $APP
    spec:
      initContainers:
        - name: init-config
          image: $IMAGE_TAG
          command: ["/bin/sh", "-c"]
          args:
            - cp -r /app/configuration/* /data/
          volumeMounts:
            - name: app-config-volume
              mountPath: "/data"
      containers:
        - name: container-$APP
          image: $IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: $PORT
          env:
            - name: NEXT_PUBLIC_BACKEND_CONNECTOR_HOST
              value: $CONNECTOR
            - name: NEXT_PUBLIC_BACKEND_TEXT_SIMILARITY
              value: $SIMILARITY
          envFrom:
            - secretRef:
                name: $APP-env
          volumeMounts:
            - name: app-config-volume
              mountPath: "/app/configuration"
      volumes:
        - name: app-config-volume
          persistentVolumeClaim:
            claimName: pvc-$APP
      nodeSelector:
        type: encoder
      tolerations:
        - key: "type"
          operator: "Equal"
          value: "encoder"
          effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: entrypoint-$APP
spec:
  type: ClusterIP
  selector:
    app: $APP
  ports:
    - port: $PORT
      targetPort: $PORT
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-$APP
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  tls:
    - hosts:
        - $URL
      secretName: $URL-tls
  rules:
    - host: $URL
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: entrypoint-$APP
                port:
                  number: $PORT
