version: "3"

services:
  traefik:
    image: traefik:v1.7-alpine
    container_name: llm_traefik
    restart: always
    ports:
      - "443:443"
      - "80:80"
    command: >
      sh -c "sh /etc/traefik/acme/acme.sh;
      traefik 
      --logLevel='WARN'
      --InsecureSkipVerify=true
      --defaultentrypoints=https,http
      --entryPoints='Name:http Address::80 Redirect.EntryPoint:https'
      --entryPoints='Name:https Address::443 TLS'
      --retry
      --docker
      --docker.endpoint='unix:///var/run/docker.sock'
      --docker.exposedbydefault=false
      --docker.watch=true
      --acme
      --acme.storage=/etc/traefik/acme/acme.json
      --acme.email=mayank.g@smarter.codes
      --acme.entryPoint=https
      --acme.onHostRule=true
      --acme.httpchallenge.entrypoint=http"
    volumes:
      - ./acme:/etc/traefik/acme
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      options:
        max-size: "50m"
        max-file: "3"
    networks:
      - docker_net
    labels:
      - "traefik.port=8080"

  llm-chatbot:  
    image: $IMAGE_TAG
    container_name: llm-chatbot
    restart: always
    logging:
      options:
        max-size: "50m"
        max-file: "3"
    command: [ "npm", "run", "dev" ]
    labels:
      - "traefik.port=80"
      - "traefik.enable=true"
      - "traefik.backend=llm-chatbot"
      - "traefik.protocol=http"
      - "traefik.frontend.rule=Host:$HOST"
    env_file:
      - .env
    networks:
      - docker_net
      
networks:
  docker_net:
    driver: bridge
